//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDinhDuong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucDon
    {
        public string Id { get; set; }
        public string IdMonAn { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string IdNguoiDung { get; set; }
        public string GhiChu { get; set; }
        public Nullable<double> Calo { get; set; }
        public Nullable<double> Carb { get; set; }
        public Nullable<double> Protein { get; set; }
        public Nullable<double> Fat { get; set; }
        public string Name { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
